'$schema' = 'https://starship.rs/config-schema.json'

format = """
[î‚¶](#d65d0e)\
$os\
$username\
$hostname\
[î‚°](bg:#d79921 fg:#d65d0e)\
$shell\
$directory\
[î‚°](fg:#d79921 bg:#689d6a)\
$git_branch\
$git_status\
[î‚°](fg:#689d6a bg:#458588)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[î‚°](fg:#458588 bg:#665c54)\
$docker_context\
$conda\
[î‚°](fg:#665c54 bg:#3c3836)\
$time\
[î‚´ ](fg:#3c3836)\
$line_break$character"""

right_format = "$aws$custom"

[os]
disabled = false
style = "bg:#d65d0e fg:#fbf1c7"

[os.symbols]
Windows = "ó°²"
Ubuntu = "ó°•ˆ"
SUSE = "ïŒ”"
Raspbian = "ó°¿"
Mint = "ó°£­"
Macos = "ó°€µ"
Manjaro = "ïŒ’"
Linux = "ó°Œ½"
Gentoo = "ó°£¨"
Fedora = "ó°£›"
Alpine = "ïŒ€"
Amazon = "ï‰°"
Android = "îœ"
Arch = "ó°£‡"
Artix = "ó°£‡"
EndeavourOS = "ï†—"
CentOS = "ïŒ„"
Debian = "ó°£š"
Redhat = "ó±„›"
RedHatEnterprise = "ó±„›"
Pop = "ïŒª"

[username]
show_always = true
style_user = "bg:#d65d0e fg:#fbf1c7"
style_root = "bg:#d65d0e fg:#fbf1c7"
format = '[ $user]($style)'

[hostname]
ssh_only = false
#format = "[$hostname]($style)"
format = "[ ]($style)"
trim_at = "-"
style = "bg:#d65d0e fg:#fbf1c7"
disabled = false

[shell]
disabled = false
style = "fg:#fbf1c7 bg:#d79921"
#format = '[ âš¡$indicator ]($style)'
format = '[ âš¡]($style)'
bash_indicator = "ï’‰"
fish_indicator = "ïœ¹"
unknown_indicator = "â“"

[directory]
style = "fg:#fbf1c7 bg:#d79921"
format = "[$path ]($style)"
truncation_length = 2
truncation_symbol = "â€¦/"

[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ó°š "
"Pictures" = "ï€¾ "
"Developer" = "ó°²‹ "

[cmd_duration]
min_time = 2000  # Show command duration over 2 seconds (2000ms)
format = " took [$duration](bold #d3869b)"

[git_branch]
symbol = "ï˜"
style = "bg:#689d6a"
format = '[[ $symbol $branch ](fg:#fbf1c7 bg:#689d6a)]($style)'

[git_commit]
commit_hash_length = 8
style = "bold white"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[git_status]
conflicted = "âš”ï¸ "
ahead = "ğŸï¸ ğŸ’¨ Ã—${count} "
behind = "ğŸ¢ Ã—${count} "
diverged = "ğŸ”± ğŸï¸ ğŸ’¨ Ã—${ahead_count} ğŸ¢ Ã—${behind_count} "
untracked = "ğŸ›¤ï¸  Ã—${count} "
stashed = "ğŸ“¦ "
modified = "ğŸ“ Ã—${count} "
staged = "ğŸ—ƒï¸  Ã—${count} "
renamed = "ğŸ“› Ã—${count} "
deleted = "ğŸ—‘ï¸  Ã—${count} "
style = "fg:#fbf1c7 bg:#689d6a"
format = "[$all_status$ahead_behind](fg:#fbf1c7 bg:#689d6a)"

[nodejs]
symbol = "îœ˜"
style = "bg:#458588"
format = '[[ $symbol( $version) ](fg:#fbf1c7 bg:#458588)]($style)'

[c]
symbol = "î˜ "
style = "bg:#458588"
format = '[[ $symbol( $version) ](fg:#fbf1c7 bg:#458588)]($style)'

[rust]
symbol = "î¨"
style = "bg:#458588"
format = '[[ $symbol( $version) ](fg:#fbf1c7 bg:#458588)]($style)'

[golang]
symbol = "î˜§"
style = "bg:#458588"
format = '[[ $symbol( $version) ](fg:#fbf1c7 bg:#458588)]($style)'

[php]
symbol = "î˜ˆ"
style = "bg:#458588"
format = '[[ $symbol( $version) ](fg:#fbf1c7 bg:#458588)]($style)'

[java]
symbol = "î‰–"
style = "bg:#458588"
format = '[[ $symbol( $version) ](fg:#fbf1c7 bg:#458588)]($style)'

[kotlin]
symbol = "î˜´"
style = "bg:#458588"
format = '[[ $symbol( $version) ](fg:#fbf1c7 bg:#458588)]($style)'

[haskell]
symbol = "î˜Ÿ"
style = "bg:#458588"
format = '[[ $symbol( $version) ](fg:#fbf1c7 bg:#458588)]($style)'

[python]
symbol = "î˜†"
style = "bg:#458588"
format = '[[ $symbol( $version) ](fg:#fbf1c7 bg:#458588)]($style)'

[package]
symbol = "ğŸ“¦"
style = "bg:#458588"
format = '[[ $symbol( $version) ](fg:#fbf1c7 bg:#458588)]($style)'

[docker_context]
symbol = "ïŒˆ"
style = "bg:#665c54"
format = '[[ $symbol( $context) ](fg:#83a598 bg:#665c54)]($style)'

[conda]
style = "bg:#665c54"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:#665c54)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#3c3836"
format = '[[ ïº $time ](fg:#fbf1c7 bg:#3c3836)]($style)'

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡"
discharging_symbol = "âš "
format = "[$symbol$percentage]($style) "

[[battery.display]]
threshold = 30
style = "bold #fabd2f"

[[battery.display]]
threshold = 15
style = "bold #fb4934"

[memory_usage]
format = "$symbol [${ram}]($style) "
threshold = 75
style = "bold #fe8019"
symbol = "ğŸ§ "
disabled = false

[[memory_usage.display]]
threshold = 50
style = "bold #fabd2f"  # yellow warning

[[memory_usage.display]]
threshold = 75
style = "bold #fb4934"  # red critical

[jobs]
symbol = "âœ¦"
style = "bold #83a598"
format = "[$symbol]($style) "

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[ï²](bold fg:#98971a)'
error_symbol = '[ï²](bold fg:#cc241d)'
vimcmd_symbol = '[ï´](bold fg:#98971a)'
vimcmd_replace_one_symbol = '[ï´](bold fg:#b16286)'
vimcmd_replace_symbol = '[](bold fg:#b16286)'
vimcmd_visual_symbol = '[](bold fg:#d79921)'

[aws]
format = '[$symbol$region]($style) '
symbol = "â˜ï¸  "
style = "bold white"

[custom.prompt]
command = "python ~/.config/starship/starship_manager.py prompt"
when = true
format = "[$output]($style) "
style = "bold #83a598"
# It is recommended to run the cache update in the background periodically.
# For example, you can use a cron job to run the following command every 10 minutes:
# */10 * * * * python ~/.config/starship/starship_manager.py update_cache